---

stages:
    - test
    - mirror
    - cleanup

nodejs-test:
    stage: test
    script:
        - export COMPOSE_PROJECT_NAME="${CI_PIPELINE_ID}-nodejs-data-grid"
        - export COMPOSE_FILE=docker-compose.ci.yml
        - make ${COMPOSE_FILE} test

mirror:
    stage: mirror
    script:
        - "curl -X POST -F token=${MIRROR_TOKEN} -F ref=master -F variables\\[REPO\\]=nodejs-data-grid https://gitlab.hanaboso.net/api/v4/projects/38/trigger/pipeline"
    only:
        - master

cleanup:
    stage: cleanup
    when: always
    script:
        - export COMPOSE_PROJECT_NAME="${CI_PIPELINE_ID}-nodejs-data-grid"
        - export COMPOSE_FILE=docker-compose.ci.yml
        - make ${COMPOSE_FILE} docker-down-clean || echo "cleanup phase failed"
