---

stages:
    - test
    - cleanup

nodejs-test:
    stage: test
    script:
        - export COMPOSE_FILE=docker-compose.ci.yml
        - make ${COMPOSE_FILE} test

cleanup:
    stage: cleanup
    when: always
    script:
        - export COMPOSE_PROJECT_NAME="${CI_PIPELINE_ID}-mongoDataGrid"
        - make docker-down-clean || echo "cleanup phase failed"
